# Generated by Django 3.0.3 on 2020-03-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensePlate', models.CharField(max_length=7)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('prediction', models.CharField(max_length=200)),
            ],
        ),
    ]
